title:       "Operating Systems 2021-1 (OS211)"
version:     "6.1--17-Apr-2021"
copyright:   "2021-2021"
description: >- 
  Gas mengmantap!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Jonathan Amadeus"
address:          "Tangerang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://hardjoe.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/HardJoe/os211/"
urlghpage:        "https://hardjoe.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

